--- 
- name: Check current RAM usage
  hosts: all
  gather_facts: true

  tasks:         
    - name: Capture Timestamp
      shell: date +"%Y%m%d%H%M%S"
      register: current_date_time

    - debug: 
        msg: "HOST: {{ ansible_inventory_hostname }}"
    - debug: 
        msg: "timestamp: {{ current_date_time }}"
        

    - debug: 
        msg: | 
          hostname :
          --- MEMORY ----
          Used  : {{ ansible_memory_mb.real.used }}
          Free  : {{ ansible_memory_mb.real.free }}
          Total : {{ ansible_memory_mb.real.total }} 
          --- CACHE ----
          Used  : {{ ansible_memory_mb.cache.used }}
          Free  : {{ ansible_memory_mb.cache.free }}
          Total : {{ ansible_memory_mb.cache.total }} 
          --- SWAP ----
          Total : {{ ansible_memory_mb.swap.used }} 
          Total : {{ ansible_memory_mb.swap.free }} 
          Total : {{ ansible_memory_mb.swap.total }} 
  