--- 
- name: Update system packages 
  hosts: all
  gather_facts: true
  become: true
  tasks: 
    - name: Install all software package updates
      package:
        name: "*"
        state: "latest" 

    - name: Check system package (Redhat/CentOS)
      yum:
      list: installed
      register: result
