--- 
- name: DUMP LOGS 
  hosts: all
  gather_facts: true
  become: true
  tasks:       
    - name: Capture Timestamp
      shell: date +"%Y%m%d%H%M%S"
      register: current_date_time

    - name: Check the logs (Debian/Ubuntu)
      shell: grep "`date --date="today" +%b\ %e`" {{ log_file }}
      become: yes
      register: log_messages
      ignore_errors: truei
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' 

    - name: Check the logs (Redhat/CentOS)
      shell: grep "`date --date="today" +%b\ %e`" {{ log_file }}
      become: yes
      register: log_messages
      ignore_errors: truei
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat'

    - name: Logs Output
      debug: 
        msg: "{{ log_messages.stdout_lines }}"
    
    - name: Ensure /tmp directory exists
      file: 
        path: '/tmp' 
        state: directory 
        mode: 0755

    - name: Deploy Template Output
      template: 
        src: logs_output.txt.j2 
        dest: "/tmp/logs-{{ inventory_hostname }}-{{ current_date_time.stdout }}.txt"

    - name: Fetch the output file
      fetch: 
        src: "{{ dump_dir }}/logs-{{ inventory_hostname }}-{{ current_date_time.stdout }}.txt"
        dest: "{{ dump_dir }}/logs-{{ inventory_hostname }}-{{ current_date_time.stdout }}.txt" 
        flat: true


