--- 
- name: Check Listed Running Services
  hosts: all
  gather_facts: true
  become: true
  vars_files:
    - ../vars/main.yml
  tasks: 

    # service_name var can be changed under ../vars/main.yml 
    - name: Check if {{ service_name }}  is running
      command: systemctl status {{ service_name }}
      register: result
      ignore_errors: yes

    - name: showing report
      debug:
      var: result.stdout
