--- 
- name: Check Listed Running Services
  hosts: all
  gather_facts: true
  become: true
  vars_files:
    - ../vars/main.yml
  tasks: 
  - name: Get current date time
    shell: date +"%Y%m%d%H%M%S"
    register: current_date_time

  - name: Install sysstat to ensure that sar commmand is available
    package:
      name: sysstat
      state: present

  - name: check if and when sar data was last collected
    stat:
      path: /tmp/data.sar
    register: sar_data_stat

  - name: collect SAR stats
    command: sar -o /tmp/data.sar 2 150
     async: 310
     poll: 5
      # check when was the stats file last modified and compare to current unix timestamp - 30 seconds
      # therefore we only collect stats if stats were last collected longer than 30 sec ago
    when: "ansible_date_time.epoch|int -30 > sar_data_stat.stat.mtime|int"
    notify: prep sar file


  - name: Create dump directory
    file: path={{ dump_dir }} state=directory mode=0755

  - name: Template file
    template: 
      src: sar_output.txt.j2 
      dest: {{ dump_dir }}/sar-{{ inventory_hostname }}-{{ current_date_time.stdout }}.txt

  - name: Fetch the output file
    fetch: 
      src: {{ dump_dir }}/sar-{{ inventory_hostname }}-{{ current_date_time.stdout }}.txt 
      dest: {{ dump_dir }}/sar-{{ inventory_hostname }}-{{ current_date_time.stdout }}.txt 
      flat=: yes


