--- 
- name: DUMP LOGS 
  hosts: all
  gather_facts: true
  tasks:
    - name: Setting variable for log_file
      set_fact:
        log_file: "/var/log/syslog"

    - name: Capture Timestamp
      shell: date +"%Y%m%d%H%M%S"
      register: current_date_time

    - name: Check the logs 
      shell: " grep `date --date="today" +%b\ %e' /var/log/syslog'` "
      register: log_messages 

    - name: Create dump directory
      file: 
        path: "/tmp/dump" 
        state: directory 
        mode: 0755
      register: dump_dir

    - name: Deploy Template Output
      template: 
        src: "logs/logs_output.j2"
        dest: "{{ dump_dir }}/logs-{{ inventory_hostname }}-{{ current_date_time.stdout }}.txt"

    - name: Fetch the output file
      fetch: 
        src: "{{ dump_dir }}/logs-{{ inventory_hostname }}-{{ current_date_time.stdout }}.txt"
        dest: "{{ dump_dir }}/logs-{{ inventory_hostname }}-{{ current_date_time.stdout }}.txt"
        flat: yes

