--- 
- name: Install system packages 
  hosts: all
  gather_facts: true
  become: true
  tasks:  
    - name: Install specified software package updates
      package:
        name: "{{ item }}"
        state: latest
      with_items: "{{ system_packages }}"
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat'

    - name: Install specified software package updates
      package:
        name: "{{ item }}"
        state: latest
      with_items: "{{ system_packages }}"
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat'

