--- 
- name: Print Todays system logs 
  hosts: all
  gather_facts: true
  become: true
  tasks:  
    - name: Remove specified software packages
      package:
        name: "{{ item }}"
        state: absent
      with_items: "{{ purged_packages }}"
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat'

    - name: Remove specified software packages
      package:
        name: "{{ item }}"
        state: absent
      with_items: "{{ purged_packages }}"
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat'

