--- 
- name: Checking connectivity with PING
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Confirming OS Family
      ansible.builtin.debug:
        msg: " {{ ansible_hostname }} os_family is: '{{ ansible_os_family }}' "
    - name: Heat Check
      ansible.builtin.ping: 

 