--- 
- name: Checking connectivity with PING
  hosts: all
  gather_facts: true
  tasks:
    - name: Heat Check
      ansible.builtin.ping:

    - name: Confirming System Details
      debug:
        msg: |
          hostname :
          --- System Details ----
          {{ ansible_hostname }} os_family is: '{{ ansible_os_family }}
          {{ ansible_hostname }} package manager: {{ ansible_pkg_mgr }}
          {{ ansible_hostname }} distribution: {{ ansible_distribution }}
          {{ ansible_hostname }} distro version: {{ ansible_distribution_major_version }}
          {{ ansible_hostname }} release number: {{ ansible_distribution_release }}
          {{ ansible_hostname }} version number: {{ ansible_distribution_version }}
          --- MEMORY ----
          Used  : {{ ansible_memory_mb.real.used }}
          Free  : {{ ansible_memory_mb.real.free }}
          Total : {{ ansible_memory_mb.real.total }}