---
- hosts: all
  gather_facts: true
  vars_files:
    - ../vars/main.yml
  tasks:
    - name: Confirming OS Family
      ansible.builtin.debug:
        msg: " {{ ansible_hostname }} os_family is: '{{ ansible_os_family }}' "

    - name: Create "{{ item }}"
      ansible.builtin.user:
        name: "{{ item }}"
        state: present
        append: true
        groups: wheel
      loop: "{{ users_list }}"
      when: ansible_facts['os_family'] == "RedHat"

    # No wheel group on Ubuntu Systems
    - name: Creating User
      ansible.builtin.user:
        name: "{{ item }}"
        state: present 
      loop: "{{ users_list }}"
      when: ansible_facts['os_family'] == "Debian"
